### ISSUE TITLE
- [ ] Realizar Prototipo baja o mediana fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sn_ppi2020#10]

**Comment by SebastianManjarres11** [comment]
[     https://drive.google.com/drive/folders/1qxY4ggAxfMBUmSSYicoEhMheY9ggB0dl?usp=sharing  ](url)

**Comment by SebastianManjarres11** [comment]
``
![IMG-20200722-WA0036](https://user-images.githubusercontent.com/65975910/89105074-bb33ea00-d3e3-11ea-827c-42ef15d57f96.jpg)
![IMG-20200722-WA0035](https://user-images.githubusercontent.com/65975910/89105075-bbcc8080-d3e3-11ea-9369-788ed2e95ae1.jpg)
![IMG-20200722-WA0034](https://user-images.githubusercontent.com/65975910/89105077-bc651700-d3e3-11ea-937c-a5b378efb015.jpg)
![IMG-20200722-WA0033](https://user-images.githubusercontent.com/65975910/89105078-bc651700-d3e3-11ea-8db1-a110db8ccda3.jpg)
![IMG-20200722-WA0032](https://user-images.githubusercontent.com/65975910/89105079-bcfdad80-d3e3-11ea-9007-f71714d39cb3.jpg)
![IMG-20200722-WA0031](https://user-images.githubusercontent.com/65975910/89105080-bcfdad80-d3e3-11ea-84fe-edab0accd555.jpg)
![IMG-20200722-WA0030](https://user-images.githubusercontent.com/65975910/89105081-bcfdad80-d3e3-11ea-893e-cd5521475ab1.jpg)
![IMG-20200722-WA0029](https://user-images.githubusercontent.com/65975910/89105082-bd964400-d3e3-11ea-8e69-620ba3ca8701.jpg)
![IMG-20200722-WA0028](https://user-images.githubusercontent.com/65975910/89105083-be2eda80-d3e3-11ea-890d-d2ec25705e68.jpg)
