### ISSUE TITLE
- [ ] Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sn_ppi2020#16]

**Comment by JohnFlorez25** [comment]
@SebastianManjarres11 @miguel588 @JuanRodriguez8 para dentro de 8 días deben tener la evidencia del Modelo entidad relación en la wiki, esta actividad la han venido desarrollando con la profesora Luisa y es ella quien les debe aprobar y validar dicho modelo. Adjunto imagen de ejemplo 
![modelo-e-r](https://user-images.githubusercontent.com/22262727/93924016-c4ea1780-fcd9-11ea-9f70-060e9d2d0b1e.png)

**Comment by SebastianManjarres11** [comment]
![Untitled Document](https://user-images.githubusercontent.com/65975910/97460173-882dc380-190a-11eb-97ae-e0640c6b0d5a.png)

**Comment by SebastianManjarres11** [comment]
![Uploading Untitled Document (1).png…]()

**Comment by SebastianManjarres11** [comment]
![Untitled Document (2)](https://user-images.githubusercontent.com/65975910/98410305-689d4600-2042-11eb-915e-8ebc8c7d5933.png)
