### ISSUE TITLE
- [ ] Describir cada uno de los interesados

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_sn_ppi2020#4]
Profesor en la wiki ya esta la descripcion de los interesados si tiene alguna sugerencia me la puede decir

**Comment by SebastianManjarres11** [comment]
![20200630_151642](https://user-images.githubusercontent.com/65975910/86174265-f2626300-bae6-11ea-9ac7-64149d8bbc58.jpg)
